### PR TITLE
Adding bioentity endpoints

### PR DESCRIPTION
**Pull request by pnavada**
Added New Endpoints for Querying Bioentity Information

Files added/modified:
1. `indra_cogex/apps/bioentity/api.py` – Contains the newly defined endpoints for querying bioentity information.
2. `indra_cogex/apps/queries_web/__init__.py` – Created `query_ns` using `flask_restx.Namespace` instead of api. Defined `query_model` from `query_ns` instead of api.
3. `indra_cogex/apps/rest_api.py` – Created this file to define the api and added both `bioentity_ns` and `query_ns` to it.
4. `indra_cogex/apps/wsgi.py` – Now imports api from `apps/rest_api.py instead of queries_web.__init__.py`.

This PR also updates `url_for` calls in the `home.html` template, superseding #184.

### CODE REVIEW

**Comment by kkaris** [comment]
I tried out the code quickly locally and what I checked out looked good.

A couple of things:

- The code needs to be rebased on the latest main
- Add description of what this PR does: which files are changes and for what purpose they were changed (i.e., add new endpoints, what they do, etc..)

**Comment by kkaris** [comment]
Also, make sure that the queries web module isn't affected by this PR by trying out some of the endpoints

**Comment by pnavada** [comment]
(.venv) navada@Pruthvis-MBP bioentity % git rebase main
Current branch develop is up to date.

Rebasing looks fine to me. The branch seems to be upto date with the latest main changes

**Comment by pnavada** [comment]
Added the file changes to the PR description

**Comment by pnavada** [comment]
Added separate models for each biomolecule entity (kinase, phosphatase, and transcription factor) to include distinct examples.

**Comment by kkaris** [comment]
> Rebasing looks fine to me. The branch seems to be up to date with the latest main changes

Did you fetch the latest updates from gyorilab? I think your `main` branch might be out of sync with the gyorilab `main` branch.

**Comment by kkaris** [comment]
I rebased on the latest `main` on `gyorilab` and did some formatting updates. A commit from [another PR](https://github.com/gyorilab/indra_cogex/pull/184) is tagging along here as well.

**Review by kkaris — APPROVED** [review]
Looks good!

**Pull request merged**
